FROM apache/spark-py:latest

USER root

WORKDIR /app

COPY consumer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer/consumer.py .

COPY submit.sh .
RUN chmod +x submit.sh

CMD ["./submit.sh"]
